### ISSUE TITLE
Cátia's 1st Issue!

### ISSUE THREAD

**Issue by joaosantos15** [joaosantos15/knowledge-exchange-ist#7]
Welcome, @catiafortunato!

This is your first issue. You can write cool stuff here, using Github's Markdown.
# Things such as this
## Or this
_Or this_
**Or this**

All of this, by the way is written in the following form:
```
# Things such as this
## Or this
_Or this_
**Or this**
```

Also, you can call people by doing this `@catiafortunato` and you can also reference other issues by doing this `#issueNumber`.

Now please say something!

**Comment by joaosantos15** [comment]
As you can see, I've created issues for most users (one for Cátia, #7, for Joana, #8, for me, #10 and one for André, #9)  All these issues are part of the `Everyone's first issues` milestone. You can check the progress of the milestone [here](https://github.com/joaosantos15/knowledge-exchange-ist/milestones)
> Note: To put a link in text, do the following:
> ` [this is what you read](http://www.This-Is-The-Link.com)`

**Comment by catiafortunato** [comment]
## My first issue 

Hello, @joaosantos15 !

This is a great way to start this knowledge exchange! :star2:

![GitHub Logo](https://assets-cdn.github.com/images/modules/open_graph/github-octocat.png)

**Comment by joaosantos15** [comment]
And it also has checklists. So you can:
- [x] Get
- [ ] Everything
- [ ] Done

> **Tip:**
> ```
>- [x] Get
>- [ ] Everything
>- [ ] Done```

**Comment by catiafortunato** [comment]
- [x] First issue
- [x] First pull request

**Comment by joaosantos15** [comment]
You can also mention pull requests, such as #6

**Comment by joaosantos15** [comment]
And then the pull request's page shows the issues that have referenced it (such as this one)
![screen shot 2018-04-07 at 16 27 09](https://user-images.githubusercontent.com/10178757/38456821-aa9dc2e6-3a80-11e8-82d0-26a3310c16ed.jpg)

**Comment by catiafortunato** [comment]
#5 and #6 are mine ! 💪

**Comment by joaosantos15** [comment]
Cool! Now go ahead and create a new issue for @joanaantunes96 to make her first contribution. Explain her how to add [this blog post](https://www.fs.blog/2013/12/stop-reading-news/) to the [blogposts document](https://github.com/joaosantos15/knowledge-exchange-ist/blob/master/docs/blogs.md) 🚀
After that, close this issue ;)

**Comment by joaosantos15** [comment]
@catiafortunato You can go ahead and close this issue 🎉
